# Generated by Django 5.0.6 on 2025-03-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipient",
                    models.CharField(
                        help_text="Recipient's email, phone number, or device ID",
                        max_length=255,
                    ),
                ),
                ("message", models.TextField(help_text="Notification content")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("E", "Email"),
                            ("S", "Sms"),
                            ("P", "Push"),
                            ("D", "Dev"),
                        ],
                        help_text="Type of notification",
                        max_length=10,
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the notification was sent",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=False,
                        help_text="Delivery status: True if sent successfully",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-sent_at"],
            },
        ),
    ]
